name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAPI_SECRET_KEY }}
          LANGUAGE: Korean
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4o
          PROMPT: 코드 자체에 집중해서 리뷰해 주세요. 실행 맥락이나 추측은 피하고, 현재 제공된 코드 범위 내에서만 피드백을 부탁드립니다. 불필요한 리뷰는 생략해 주세요.
          top_p: 1
          temperature: 0.7
          max_tokens: 1500
          MAX_PATCH_LENGTH: 5000
          IGNORE_PATTERNS: /node_modules/**/*,*.md,*.log,*.txt 
